name = "cf-nix-cache"
main = "build/index.js"
compatibility_date = "2026-05-14"

[build]
command = "worker-build --dev"

[[r2_buckets]]
binding = "CF_NIX_WORKER_BUCKET"
bucket_name = "nix-bucket-dev"

[vars]
# Uploads in local dev need a GitHub token with push access to this repo.
CF_NIX_WORKER_GITHUB_REPOSITORY = "cf-contrib/cf-nix-cache"
